#!/usr/bin/env bash

if command -v golangci-lint ; then
    golangci-lint run
else
    docker run --rm -v $(pwd):/app -v ~/.cache/golangci-lint/v1.61.0:/root/.cache -w /app golangci/golangci-lint:v1.61.0 golangci-lint run -v
fi
