#!/usr/bin/env bash
set -e

REPO="$(cd "$(dirname "$0")/.." && pwd)"
GOAL="$REPO/../goal"

echo "Pulling goal repo..."
git -C "$GOAL" pull --rebase --prune

GOALSHA="$(git -C "$GOAL" rev-parse HEAD)"
echo "Goal HEAD: $GOALSHA"

echo "Syncing goallib/ from $GOAL/lib ..."
rm -rf "$REPO/goallib"
mkdir -p "$REPO/goallib"
find "$GOAL/lib" -type f -name '*.goal' | xargs -I {} cp {} "$REPO/goallib/"

cat > "$REPO/goallib/README.md" <<EOF
# Vendored Goal Standard Library

Files in this directory are copied from the [Goal](https://codeberg.org/anaseto/goal)
project's \`lib/\` directory and embedded into the ari binary at build time.

Pulled from Goal at Git commit: \`$GOALSHA\`

---

## License & Copyright

The Goal standard library files are copyright © their original author and are
used here under the terms of the ISC Licence:

> Copyright (c) 2022 Yon <anaseto@bardinflor.perso.aquilenet.fr>
>
> Permission to use, copy, modify, and distribute this software for any
> purpose with or without fee is hereby granted, provided that the above
> copyright notice and this permission notice appear in all copies.
>
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
> WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
> MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
> ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
> WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
> ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
> OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
EOF

echo "Done. goallib/ updated and README written."
