name: build

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - uses: actions/setup-go@8e57b58e57be52ac95949151e2777ffda8501267
        with:
          go-version: "1.24"
      - name: build-wasm
        run: |
          ./script/build-wasm
      - name: test
        run: |
          ./script/test
