name: build

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: "1.24"
      - name: build-wasm
        run: |
          ./script/build-wasm
      - name: test
        run: |
          ./script/test
