name: golangci-lint
on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9f265659d3bb64ab1440b03b12f4d47a24320917
      - uses: actions/setup-go@8e57b58e57be52ac95949151e2777ffda8501267
        with:
          go-version: "1.24"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@f9e969abf518e6dd0876e758f2ce8bf58bb5d56b
